apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: decision-tree-navigator
  namespace: tada
  labels:
    team: tada
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://beslutt.nav.no
  resources:
    requests:
      cpu: "10m"
      memory: "32Mi"
  replicas:
    max: 1
    min: 1
  liveness:
    path: /
